#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           9

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# wallpaper
# feh --bg-scale Pictures/wallpaper/station.jpg &

wal -i Pictures/wallpaper/turtlehouse.png --saturate 0.9 &

# autostart
dunst &
sxhkd &
xmodmap ~/.config/keyboard/Xmodmap &
sh ~/.config/keyboard/xcape &
sh ~/.config/polybar/launch.sh &
picom --experimental-backends &
